### ISSUE TITLE
Error bars are not moved correctly when switching to linear scale

### ISSUE THREAD

**Issue by jl-wynen** [scipp/plopp#152] opened 2023-02-03 14:30 UTC
Using the example below, when turning on `logy` and then off again, the markers move in the plot but not the errorbars. The same happens when plotting with `norm='log'` and then switching to linear scale using the button.

![errorbar-bug](https://user-images.githubusercontent.com/11393224/216628487-263a9f96-84d4-4d9f-b8e9-8e9b293c4786.png)

**Comment by nvaytet** [comment] 2023-02-06 08:47
Two things:
1. I cannot reproduce this behaviour with latest `main`.
2. It seems in your example that the errorbars are in the correct place, and it's the round markers that are wrong (they are all under 1, when the values should span 0-10?)

**Comment by nvaytet** [comment] 2023-02-06 09:02
![Screenshot at 2023-02-06 10-01-00](https://user-images.githubusercontent.com/39047984/216929436-5cb8973f-48e8-442e-81cd-51f849c18287.png)

**Comment by SimonHeybrock** [comment] 2023-02-06 09:07
Can you please post a code example, so others can test?

**Comment by SimonHeybrock** [comment] 2023-02-06 10:43
CNR either.

**Comment by jl-wynen** [comment] 2023-02-06 12:16
Neils code reproduces it for me with plopp on `main` with
```
ipykernel                 6.16.0             pyh210e3f2_0    conda-forge
ipympl                    0.9.2              pyhd8ed1ab_0    conda-forge
ipython                   8.5.0              pyh41d4057_1    conda-forge
ipywidgets                8.0.2              pyhd8ed1ab_1    conda-forge
jupyter_client            7.3.5              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py38h578d9bd_0    conda-forge
jupyter_server            1.19.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.7              pyhd8ed1ab_0    conda-forge
matplotlib                3.6.3            py38h578d9bd_0    conda-forge
matplotlib-base           3.6.3            py38hd6c3c57_0    conda-forge
```

**Comment by SimonHeybrock** [comment] 2023-02-06 12:25
I had mpl 3.5, but it still works after update to 3.6, so it must be sth. else.

**Comment by SimonHeybrock** [comment] 2023-02-06 12:26
Do you get the same problem without `widget` mode?

**Comment by jl-wynen** [comment] 2023-02-06 12:53
> Do you get the same problem without widget mode?

There are no buttons to click without widgets...

**Comment by nvaytet** [comment] 2023-02-07 10:42
I get the same bug as @jl-wynen with `mpl=3.6.3`. Related to https://github.com/matplotlib/matplotlib/issues/25124?
Here is a mwe with mpl only:
```Py
import matplotlib.pyplot as plt
import numpy as np
%matplotlib widget

a = np.arange(10.)

fig, ax = plt.subplots()
ax.plot(a, 'o')
ax.errorbar(a, a, yerr=np.sqrt(a))
```
Then, in **two separate jupyter cells**, run
```Py
ax.set_yscale('log')
```
```Py
ax.set_yscale('linear')
```
(running in the same cell does not show the bug)
![Screenshot at 2023-02-07 11-41-35](https://user-images.githubusercontent.com/39047984/217222876-a1495a59-679f-490d-ae5c-bf361ef2e345.png)

**Comment by nvaytet** [comment] 2023-02-07 10:43
@jl-wynen can you confirm that the bug is not there with `mpl=3.6.2`?

**Comment by jl-wynen** [comment] 2023-02-07 12:41
> @jl-wynen can you confirm that the bug is not there with mpl=3.6.2?

I can confirm this.

**Comment by nvaytet** [comment] 2023-02-07 12:45
Closing for now, as it's out of our control.

**Closed by nvaytet** 2023-02-07 12:45 UTC
Labels: bug

**Comment by SimonHeybrock** [comment] 2023-02-08 06:04
Why is it out of our control? Can't we exclude this version?

**Comment by nvaytet** [comment] 2023-02-08 08:32
We could, but I am not sure it's worth it? There is already a fix merged that will be part of the next mpl release.
